# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/charles/Coding/Python/KAS/maindlg.ui'
#
# Created: Sat Sep 12 06:34:42 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainDlg(object):
    def setupUi(self, MainDlg):
        MainDlg.setObjectName("MainDlg")
        MainDlg.resize(750, 500)
        MainDlg.setMinimumSize(QtCore.QSize(750, 500))
        self.gridLayout = QtGui.QGridLayout(MainDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(MainDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.urlLineEdit = QtGui.QLineEdit(MainDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLineEdit.sizePolicy().hasHeightForWidth())
        self.urlLineEdit.setSizePolicy(sizePolicy)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout.addWidget(self.urlLineEdit)
        self.label_2 = QtGui.QLabel(MainDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.outputNameLineEdit = QtGui.QLineEdit(MainDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputNameLineEdit.sizePolicy().hasHeightForWidth())
        self.outputNameLineEdit.setSizePolicy(sizePolicy)
        self.outputNameLineEdit.setObjectName("outputNameLineEdit")
        self.horizontalLayout.addWidget(self.outputNameLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.line = QtGui.QFrame(MainDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.outputTextBrowser = QtGui.QTextBrowser(MainDlg)
        self.outputTextBrowser.setObjectName("outputTextBrowser")
        self.gridLayout.addWidget(self.outputTextBrowser, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrapeProgressBar = QtGui.QProgressBar(MainDlg)
        self.scrapeProgressBar.setProperty("value", QtCore.QVariant(0))
        self.scrapeProgressBar.setObjectName("scrapeProgressBar")
        self.horizontalLayout_2.addWidget(self.scrapeProgressBar)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.cancelPushButton = QtGui.QPushButton(MainDlg)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.gridLayout.addWidget(self.cancelPushButton, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsPushButton = QtGui.QPushButton(MainDlg)
        self.settingsPushButton.setObjectName("settingsPushButton")
        self.verticalLayout.addWidget(self.settingsPushButton)
        self.aboutPushButton = QtGui.QPushButton(MainDlg)
        self.aboutPushButton.setObjectName("aboutPushButton")
        self.verticalLayout.addWidget(self.aboutPushButton)
        self.line_2 = QtGui.QFrame(MainDlg)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.outputLocationPushButton = QtGui.QPushButton(MainDlg)
        self.outputLocationPushButton.setObjectName("outputLocationPushButton")
        self.verticalLayout.addWidget(self.outputLocationPushButton)
        self.galleryPushButton = QtGui.QPushButton(MainDlg)
        self.galleryPushButton.setObjectName("galleryPushButton")
        self.verticalLayout.addWidget(self.galleryPushButton)
        self.scrapePushButton = QtGui.QPushButton(MainDlg)
        self.scrapePushButton.setObjectName("scrapePushButton")
        self.verticalLayout.addWidget(self.scrapePushButton)
        self.closePushButton = QtGui.QPushButton(MainDlg)
        self.closePushButton.setObjectName("closePushButton")
        self.verticalLayout.addWidget(self.closePushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.label.setBuddy(self.urlLineEdit)
        self.label_2.setBuddy(self.outputNameLineEdit)

        self.retranslateUi(MainDlg)
        QtCore.QMetaObject.connectSlotsByName(MainDlg)
        MainDlg.setTabOrder(self.urlLineEdit, self.outputNameLineEdit)
        MainDlg.setTabOrder(self.outputNameLineEdit, self.outputTextBrowser)

    def retranslateUi(self, MainDlg):
        MainDlg.setWindowTitle(QtGui.QApplication.translate("MainDlg", "Kick Ass Thread Scraper", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainDlg", "&Thread Url:", None, QtGui.QApplication.UnicodeUTF8))
        self.urlLineEdit.setToolTip(QtGui.QApplication.translate("MainDlg", "Enter the entire thread URL, of the thread you wish to scrape for images.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainDlg", " O&utput Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("MainDlg", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsPushButton.setText(QtGui.QApplication.translate("MainDlg", "S&ettings", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutPushButton.setText(QtGui.QApplication.translate("MainDlg", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLocationPushButton.setToolTip(QtGui.QApplication.translate("MainDlg", "Choose a directory to output scraped files to.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLocationPushButton.setText(QtGui.QApplication.translate("MainDlg", "&Output Location", None, QtGui.QApplication.UnicodeUTF8))
        self.galleryPushButton.setToolTip(QtGui.QApplication.translate("MainDlg", "View thread image thumbnails in a gallery and choose which images you wish to download.", None, QtGui.QApplication.UnicodeUTF8))
        self.galleryPushButton.setText(QtGui.QApplication.translate("MainDlg", "Thumb &Gallery", None, QtGui.QApplication.UnicodeUTF8))
        self.scrapePushButton.setToolTip(QtGui.QApplication.translate("MainDlg", "Scrape selected thread.", None, QtGui.QApplication.UnicodeUTF8))
        self.scrapePushButton.setText(QtGui.QApplication.translate("MainDlg", "&Scrape it!", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setText(QtGui.QApplication.translate("MainDlg", "Close", None, QtGui.QApplication.UnicodeUTF8))

